FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ api/
COPY src/ src/

EXPOSE 8000

# Executa o povoamento e em seguida levanta a API
CMD ["sh", "-c", "python src/generator.py && uvicorn api.main:app --host 0.0.0.0 --port 8000"]